// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhuaYqi4yu9P9MWkIiL5KzlHzqW0X6Poc',
    appId: '1:785197695002:web:b71c6c74ac84a9caa651a3',
    messagingSenderId: '785197695002',
    projectId: 'fruit-hub-c3e8a',
    authDomain: 'fruit-hub-c3e8a.firebaseapp.com',
    storageBucket: 'fruit-hub-c3e8a.firebasestorage.app',
    measurementId: 'G-M3RJLCV46L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogWEoGCV551gtDZ_CkFH-WrcPEr6pK50',
    appId: '1:785197695002:android:c77b511b6321880aa651a3',
    messagingSenderId: '785197695002',
    projectId: 'fruit-hub-c3e8a',
    storageBucket: 'fruit-hub-c3e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHPd4O8pwzhGyQMy877pN7HjhruZE37E',
    appId: '1:785197695002:ios:531bfb9a0ecde498a651a3',
    messagingSenderId: '785197695002',
    projectId: 'fruit-hub-c3e8a',
    storageBucket: 'fruit-hub-c3e8a.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHPd4O8pwzhGyQMy877pN7HjhruZE37E',
    appId: '1:785197695002:ios:531bfb9a0ecde498a651a3',
    messagingSenderId: '785197695002',
    projectId: 'fruit-hub-c3e8a',
    storageBucket: 'fruit-hub-c3e8a.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhuaYqi4yu9P9MWkIiL5KzlHzqW0X6Poc',
    appId: '1:785197695002:web:01880890b2398d4ca651a3',
    messagingSenderId: '785197695002',
    projectId: 'fruit-hub-c3e8a',
    authDomain: 'fruit-hub-c3e8a.firebaseapp.com',
    storageBucket: 'fruit-hub-c3e8a.firebasestorage.app',
    measurementId: 'G-TBK64XF4YV',
  );
}
